### ISSUE TITLE
大佬你好,wrangler secret put REFRESH_TOKEN这一步的时候提示 Your secret is too large, it must be 1kB or less

### ISSUE THREAD

**Issue by xiaolilir** [spencerwooo/onedrive-cf-index#88] opened 2021-01-18 09:46 UTC
卡在这了请问大佬应该如何解决啊，我看了下**REFRESH_TOKEN**有1024个字符长度

**Comment by spencerwooo** [comment] 2021-01-18 14:32
Duplicate of https://github.com/spencerwooo/onedrive-cf-index/issues/58

**Closed by spencerwooo** 2021-01-18 14:32 UTC
Labels: duplicate
